import { Product } from '../../types/products.type';
import { Category } from '../../types/category';

export const demoProducts = [
  {
    id: 1,
    product_name: 'Jacket',
    product_description: 'Jacket description goes here',
    price: 100,
    ratings: 5,
    category_id: 5,
    product_img: 'shop-1.jpg',
  },
  {
    id: 2,
    product_name: 'Purse',
    product_description: 'Very nice purse',
    price: 2,
    ratings: 3,
    category_id: 7,
    product_img: 'shop-2.jpg',
  },
  {
    id: 3,
    product_name: 'Dress',
    product_description: 'Nice Party Dress',
    price: 45,
    ratings: 4,
    category_id: 5,
    product_img: 'shop-3.jpg',
  },
  {
    id: 4,
    product_name: 'Denim Jeans',
    product_description: 'Denim Jeans',
    price: '50',
    ratings: 4,
    category_id: 4,
    product_img: 'shop-4.jpg',
  },
  {
    id: 5,
    product_name: 'Laced Boots',
    product_description: 'Premium leather boots',
    price: 65,
    ratings: 4,
    category_id: 6,
    product_img: 'shop-5.jpg',
  },
  {
    id: 6,
    product_name: 'Backpack',
    product_description: 'Spacious backpack',
    price: '20',
    ratings: 5,
    category_id: 7,
    product_img: 'shop-6.jpg',
  },
  {
    id: 7,
    product_name: 'Earrings',
    product_description: 'Beautiful earrings',
    price: 10,
    ratings: 4,
    category_id: 7,
    product_img: 'shop-7.jpg',
  },
  {
    id: 8,
    product_name: 'Scarf',
    product_description: 'Matching scarf',
    price: '30',
    ratings: 4,
    category_id: 7,
    product_img: 'shop-8.jpg',
  },
  {
    id: 9,
    product_name: 'Boots',
    product_description: 'Black leather boots',
    price: 70,
    ratings: 4,
    category_id: 6,
    product_img: 'shop-9.jpg',
  },
  {
    id: 10,
    product_name: 'Shirt',
    product_description: 'Casual cotton shirt',
    price: '35',
    ratings: 4,
    category_id: 4,
    product_img: 'shop-10.jpg',
  },
  {
    id: 11,
    product_name: 'Sunglasses',
    product_description: 'Stylish sunglasses',
    price: 15,
    ratings: 5,
    category_id: 7,
    product_img: 'shop-11.jpg',
  },
  {
    id: 12,
    product_name: 'Hat',
    product_description: 'Trendy hat',
    price: 18,
    ratings: 4,
    category_id: 7,
    product_img: 'shop-12.jpg',
  },
  {
    id: 13,
    product_name: 'Gloves',
    product_description: 'Warm winter gloves',
    price: 12,
    ratings: 4,
    category_id: 6,
    product_img: 'shop-13.jpg',
  },
  {
    id: 14,
    product_name: 'Watch',
    product_description: 'Classic wristwatch',
    price: 60,
    ratings: 5,
    category_id: 7,
    product_img: 'shop-14.jpg',
  },
  {
    id: 15,
    product_name: 'Sweater',
    product_description: 'Cozy knit sweater',
    price: 40,
    ratings: 4,
    category_id: 5,
    product_img: 'shop-15.jpg',
  },
  {
    id: 16,
    product_name: 'Shorts',
    product_description: 'Comfortable shorts',
    price: 25,
    ratings: 3,
    category_id: 4,
    product_img: 'shop-16.jpg',
  },
  {
    id: 17,
    product_name: 'Necklace',
    product_description: 'Elegant necklace',
    price: 28,
    ratings: 4,
    category_id: 7,
    product_img: 'shop-17.jpg',
  },
  {
    id: 18,
    product_name: 'Wallet',
    product_description: 'Leather wallet',
    price: 22,
    ratings: 4,
    category_id: 7,
    product_img: 'shop-18.jpg',
  },
  {
    id: 19,
    product_name: 'Blouse',
    product_description: 'Flowy blouse',
    price: 38,
    ratings: 5,
    category_id: 5,
    product_img: 'shop-19.jpg',
  },
  {
    id: 20,
    product_name: 'Running Shoes',
    product_description: 'Lightweight running shoes',
    price: 55,
    ratings: 4,
    category_id: 6,
    product_img: 'shop-20.jpg',
  },
] as Product[];

export const demoCategories = [
  {
    id: 2,
    category: 'Women',
    parent_category_id: null,
  },
  {
    id: 3,
    category: 'Kids',
    parent_category_id: null,
  },
  {
    id: 4,
    category: 'Casual Wear',
    parent_category_id: 1,
  },
  {
    id: 5,
    category: 'Party Wear',
    parent_category_id: 2,
  },
  {
    id: 6,
    category: 'Foot Wear',
    parent_category_id: 2,
  },
  {
    id: 7,
    category: 'Accessories',
    parent_category_id: 3,
  },
  {
    id: 1,
    category: 'Men',
    parent_category_id: null,
  },
] as Category[];
